services:
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data9:/var/lib/postgresql/data
    networks:
      - app-network
  
  # redis:
  #   image: "redis:7-alpine"
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

  # rabbitmq:
  #   image: "rabbitmq:4"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - app-network

volumes:
  postgres_data9:

networks:
  app-network:
